# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml
#  ingress:
#    enabled: true
#    className: nginx
#    host: "localhost"

global:
  image:
    tag: latest
    # pullPolicy: Always

operate:
  image:
    tag: 8.5.4

tasklist:
  image:
    tag: 8.5.2

connectors:
  enabled: false

optimize:
  enabled: false

webModeler:
  enabled: false 

identity:
  image:
    tag: 8.5.3
  enabled: true
  firstUser:
    username: demo
    password: demo.1234
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1024Mi"
      cpu: "500m"

identityKeycloak:
  enabled: "true"
  auth: 
    adminUser: "kcadmin"
    adminPassword: "admin.1234"

zeebe-gateway:
  image:
    tag: 8.5.3
  ingress:
    enabled: true
    className: nginx
    host: "localhost"
  replicas: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1024Mi"
      cpu: "500m"

zeebe:
  image:
    tag: 8.5.3
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 10Gi
  resources:
    requests:
      cpu: "1"
      memory: "512Mi"
    limits:
      cpu: "2"
      memory: "1Gi"

elasticsearch:
  image: 
    repository: "bitnami/elasticsearch"
    tag: "8.12.2"
  master:
    replicaCount: 1
    heapSize: "256m"
    # Request smaller persistent volumes.
    persistence:
      size: "15Gi"
    resources:
      requests:
        cpu: "1"
        memory: "512Mi"
      limits:
        cpu: "2"
        memory: "1Gi"



