apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:25.0.2
          args: ["start-dev"]
          resources:
            requests:
              cpu: "500m"
              memory: "1024Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          env:
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://postgres-service:5432/s3pub"
            - name: KC_DB_SCHEMA
              value: keycloak
            - name: KC_DB_PASSWORD
              value: "admin.1234"
            - name: KC_DB_USERNAME
              value: "dbadmin"
            - name: KEYCLOAK_ADMIN
              value: "kcadmin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin.1234"
            - name: "KC_HTTP_ENABLED"
              value: "true"
          ports:
            - containerPort: 8080
